apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: game-processor
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-apps-game-processor
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: apps
  name: game-processor
spec:
  rules:
  - host: game-processor.thetablestop.com
    http:
      paths:
      - backend:
          serviceName: game-processor
          servicePort: http
  tls:
  - hosts:
    - game-processor.thetablestop.com
    secretName: star-thetablestop-com
